
NDDEMO :=\
asm/NDDEMO/main/main.o\
asm/NDDEMO/dm/DMainSystem.o\
asm/NDDEMO/du/DUDvd.o\
asm/NDDEMO/du/DUMacro.o\
asm/NDDEMO/dg/DGLight.o\
asm/NDDEMO/dg/DGModel.o\
asm/NDDEMO/dg/DGModelMan.o\
asm/NDDEMO/dg/DGObject.o\
asm/NDDEMO/dg/DGObjMan.o\
asm/NDDEMO/dg/DGParts.o\
asm/NDDEMO/dg/DGRendMan.o\
asm/NDDEMO/dg/DGTexMan.o\
asm/NDDEMO/dg/DGCamera.o\
asm/NDDEMO/dg/DGPosition.o\
asm/NDDEMO/dg/DGFont.o\
asm/NDDEMO/dg/DGRendState.o\
asm/NDDEMO/dg/DGTexPro.o\
asm/NDDEMO/dg/DGAniModel.o\
asm/NDDEMO/dg/DGTexture.o\
asm/NDDEMO/dt/DTPad.o\
asm/NDDEMO/dt/DTHit.o\
asm/NDDEMO/dt/DTLight.o\
asm/NDDEMO/dt/DTGimmick.o\
asm/NDDEMO/dt/DTPlayer.o\
asm/NDDEMO/dt/DTCamera.o\
asm/NDDEMO/da/DAudio.o

DOLPHIN :=\
asm/dolphin/base/PPCArch.o
asm/dolphin/os/OS.o.o\
asm/dolphin/os/OSAlarm.o\
asm/dolphin/os/OSAlloc.o\
asm/dolphin/os/OSArena.o\
asm/dolphin/os/OSAudioSystem.o\
asm/dolphin/os/OSCache.o\
asm/dolphin/os/OSContext.o\
asm/dolphin/os/OSError.o\
asm/dolphin/os/OSExi.o\
asm/dolphin/os/OSInterrupt.o\
asm/dolphin/os/OSLink.o\
asm/dolphin/os/OSMemory.o\
asm/dolphin/os/OSMutex.o\
asm/dolphin/os/OSReboot.o\
asm/dolphin/os/OSReset.o\
asm/dolphin/os/OSResetSW.o\
asm/dolphin/os/OSRtc.o\
asm/dolphin/os/OSSerial.o\
asm/dolphin/os/OSStopwatch.o\
asm/dolphin/os/OSSync.o\
asm/dolphin/os/OSThread.o\
asm/dolphin/os/OSTime.o\
asm/dolphin/os/OSUartExi.o\
asm/dolphin/os/__start.o\
asm/dolphin/os/__ppc_eabi_init.o\
asm/dolphin/db/db.o\
asm/dolphin/mtx/mtx.o\
asm/dolphin/mtx/mtxvec.o\
asm/dolphin/mtx/mtx44.o\
asm/dolphin/mtx/vec.o\
asm/dolphin/dvd/dvdlow.o\
asm/dolphin/dvd/dvdfs.o\
asm/dolphin/dvd/dvd.o\
asm/dolphin/dvd/dvdqueue.o\
asm/dolphin/dvd/dvderror.o\
asm/dolphin/dvd/fstload.o\
asm/dolphin/vi/vi.o\
asm/dolphin/pad/Padclamp.o\
asm/dolphin/pad/Pad.o\
asm/dolphin/ai/ai.o\
asm/dolphin/ar/ar.o\
asm/dolphin/ar/arq.o\
asm/dolphin/dsp/dsp.o\
asm/dolphin/dsp/dsp_debug.o\
asm/dolphin/dsp/dsp_task.o\
asm/dolphin/gx/GXInit.o\
asm/dolphin/gx/GXFifo.o\
asm/dolphin/gx/GXAttr.o\
asm/dolphin/gx/GXMisc.o\
asm/dolphin/gx/GXGeometry.o\
asm/dolphin/gx/GXFrameBuf.o\
asm/dolphin/gx/GXLight.o\
asm/dolphin/gx/GXTexture.o\
asm/dolphin/gx/GXBump.o\
asm/dolphin/gx/GXTev.o\
asm/dolphin/gx/GXPixel.o\
asm/dolphin/gx/GXStubs.o\
asm/dolphin/gx/GXDisplayList.o\
asm/dolphin/gx/GXTransform.o\
asm/dolphin/gx/GXPerf.o

MUSYX :=\
asm/musyx/seq.o\
asm/musyx/synth.o\
asm/musyx/seq_api.o\
asm/musyx/snd_synthapi.o\
asm/musyx/stream.o\
asm/musyx/synthdata.o\
asm/musyx/synthmacros.o\
asm/musyx/synthvoice.o\
asm/musyx/synth_ac.o\
asm/musyx/synth_adsr.o\
asm/musyx/synth_dbtab.o\
asm/musyx/s_data.o\
asm/musyx/hw_dspctrl.o\
asm/musyx/hw_volconv.o\
asm/musyx/snd3d.o\
asm/musyx/snd_init.o\
asm/musyx/snd_math.o\
asm/musyx/snd_midictrl.o\
asm/musyx/snd_service.o\
asm/musyx/hardware.o\
asm/musyx/hw_aramdma.o\
asm/musyx/hw_dolphin.o\
asm/musyx/hw_memory.o\
asm/musyx/dsp_import.o\
asm/musyx/reverb_fx.o\
asm/musyx/reverb.o\
asm/musyx/chorus_fx.o


MW :=\
asm/PowerPC_EABI_Support/MetroTRK/Portable/mainloop.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/nubevent.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/nubinit.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/msg.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/msgbuf.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/serpoll.o\
asm/PowerPC_EABI_Support/MetroTRK/Os/dolphin/usr_put.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/dispatch.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/msghndlr.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/support.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/mutex_TRK.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/notify.o\
asm/PowerPC_EABI_Support/MetroTRK/Processor/ppc/Generic/flush_cache.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/mem_TRK.o\
asm/PowerPC_EABI_Support/MetroTRK/Processor/ppc/Generic/__exception.o\
asm/PowerPC_EABI_Support/MetroTRK/Processor/ppc/Generic/targimpl.o\
asm/PowerPC_EABI_Support/MetroTRK/Os/dolphin/dolphin_trk.o\
asm/PowerPC_EABI_Support/MetroTRK/Processor/ppc/Generic/mpc_7xx_603e.o\
asm/PowerPC_EABI_Support/MetroTRK/Portable/main_TRK.o\
asm/PowerPC_EABI_Support/MetroTRK/Os/dolphin/dolphin_trk_glue.o\
asm/PowerPC_EABI_Support/MetroTRK/Os/dolphin/targcont.o\
asm/PowerPC_EABI_Support/Runtime/__mem.o\
asm/PowerPC_EABI_Support/Runtime/__va_arg.o\
asm/PowerPC_EABI_Support/Runtime/global_destructor_chain.o\
asm/PowerPC_EABI_Support/Runtime/NMWException.o\
asm/PowerPC_EABI_Support/Runtime/ExceptionPPC.o\
asm/PowerPC_EABI_Support/Runtime/runtime.o\
asm/PowerPC_EABI_Support/Runtime/__init_cpp_exceptions.o\
asm/PowerPC_EABI_Support/MSL_C/PPC_EABI/abort_exit.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common/ansi_files.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/ansi_fp.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common/buffer_io.o\
asm/PowerPC_EABI_Support/MSL_C/PPC_EABI/critical_regions.ppc_eabi.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common/ctype.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common/direct_io.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common/mbstring.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common/mem.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common/mem_funcs.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common/misc_io.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common/printf.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common/string.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/uart_console_io.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wchar_io.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_frexp.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/Single_precision/hyperbolicsf.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/Single_precision/inverse_trig.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/Single_precision/trigf.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/Single_precision/common_float_tables.o\
asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/Single_precision/exponentialsf.o

NDEV :=\
asm/dolphin/AmcExi2Stubs.o\
asm/dolphin/DebuggerDriver.o\
asm/dolphin/odenotstub.o
